#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Mon Sep  3 17:09:20 2018

@author: son
"""

from socket import socket, AF_INET, SOCK_STREAM

class LazyConnection:
    def __init__(self, address, family=AF_INET, type=SOCK_STREAM):
        self.address = address
        self.family = AF_INET
        self.type = SOCK_STREAM
        self.connections = []
    def __enter__(self):
        print('start')
        sock = socket(self.family, self.type)
        print(self.address)
        sock.connect(self.address)
        self.connections.append(sock)
        return sock
    def __exit__(self, exc_ty, exc_val, tb):
        print(tb)
        self.connections.pop().close()
        
        
        

from functools import partial

conn = LazyConnection(("www.python.org",80))
with conn as s:
    s.send(b'GET /index.html HTTP/1.0\r\n')
    s.send(b'Host: www.python.org\r\n')
    s.send(b'\r\n')
    resp = b''.join(iter(partial(s.recv, 8192), b''))
    print(resp)
    
    
conn1 = LazyConnection(('www.naver.com', 80))
with conn1 as s:
    s.send(b'GET /index.html HTTP/1.0\r\n')
    s.send(b'Host: www.naver.com\r\n')
    s.send(b'\r\n')
    resp = b''.join(iter(partial(s.recv, 8192), b''))
    print(resp)
    with conn1 as s2:
            s.send(b'GET /index.html HTTP/1.0\r\n')
            s.send(b'Host: www.naver.com\r\n')
            s.send(b'\r\n')
            resp1= b''.join(iter(partial(s.recv, 8192), b''))
            print(resp1)
        
    
#with conn as s:
    

